// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Wed Sep  1 22:15:11 2021

ALU ALU_inst
(
	.ALU_controle(ALU_controle_sig) ,	// input [3:0] ALU_controle_sig
	.Entrada_A(Entrada_A_sig) ,	// input [7:0] Entrada_A_sig
	.Entrada_B(Entrada_B_sig) ,	// input [7:0] Entrada_B_sig
	.ALU_Result(ALU_Result_sig) ,	// output [7:0] ALU_Result_sig
	.CarryOut(CarryOut_sig) 	// output  CarryOut_sig
);

